title = '脑冻的洞'
baseURL = 'https://noodlefreeze.github.io'

theme = 'hugo-blog-awesome'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Languages.zh-cn]
  languageName = "Chinese"
  languageCode = "zh-cn"
  contentDir = "content/zh"
  weight = 1
  
  [Languages.zh-cn.menu]
  [[Languages.zh-cn.menu.main]]
    pageRef="/"
    name = '首页'
    url = '/'
    weight = 10
  [[Languages.zh-cn.menu.main]]
    pageRef="posts"
    name = '文章'
    url = '/posts/'
    weight = 20
  [[Languages.zh-cn.menu.main]]
    pageRef="about"
    name = '关于'
    url = '/about/'
    weight = 30

[Languages.zh-cn.params]
  sitename = "脑冻的洞"
  defaultColor = "auto" # set color mode: dark, light, auto
  mainSections = ['posts']
  dateFormat = "2006年01月02日" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.

  [Languages.zh-cn.params.author]
    avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
    intro = "脑冻的洞"
    name = "noodlefreeze"
    description = "You are... froze! ❄️"

[[params.socialIcons]]
name = "github"
url = "https://github.com/noodlefreeze"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/lenianwain"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
